### ISSUE TITLE
19. Countdown Speed

### ISSUE THREAD

**Issue by CozyRocket** [atesgoral/human-resource-machine-solutions#22]
(Wasn't sure how to submit but this gets the speed completed)

```
-- HUMAN RESOURCE MACHINE PROGRAM --

a:
b:
    INBOX   
    JUMPN    c
    JUMP     e

c:
    COPYTO   0

d:
    OUTBOX  
    BUMPUP   0
    JUMPN    d
    JUMPZ    g

e:
    COPYTO   5

f:
    OUTBOX  
    BUMPDN   5
    JUMPN    b
    JUMP     f

g:
    OUTBOX  
    JUMP     a
```

**Comment by atesgoral** [comment]
@CozyRocket Thanks for that solution. I could copy/paste and add this in on your behalf, but I'd prefer it if your name shows up in Git commit history. Could you please take a look at https://yangsu.github.io/pull-request-tutorial/ and let me know if you still need assistance in creating a PR (Pull Request)?

**Comment by CozyRocket** [comment]
That's fine!, I'm new to this whole thing and I am still getting my head around it. You can go ahead and do it.

**Comment by atesgoral** [comment]
Added. Thanks!
