### ISSUE TITLE
24-Mod-Module.size.speed.asm

### ISSUE THREAD

**Issue by nanashi-juanto** [atesgoral/human-resource-machine-solutions#52]
I am new to github and am very confused. I'm still trying to figure out how to do everything.

This does it in 11 commands and 53 steps.

-- HUMAN RESOURCE MACHINE PROGRAM --

a:
    INBOX   
    COPYTO   0
    INBOX   
    COPYTO   1
    COPYFROM 0
b:
    SUB      1
    JUMPN    c
    JUMP     b
c:
    ADD      1
    OUTBOX  
    JUMP     a

**Comment by atesgoral** [comment]
Please feel free to take your time and take a stab at issuing a Pull Request. This guide seems to be nice: https://yangsu.github.io/pull-request-tutorial/

Please let me know if you get stuck. Or let me know if you don't want to deal with it and I can incorporate your improvements on your behalf.

Thanks! :)

**Comment by nanashi-juanto** [comment]
I think I got it. I can see the pull request that I just now submitted.
