### ISSUE TITLE
24

### ISSUE THREAD

**Issue by drallieiv** [atesgoral/human-resource-machine-solutions#55]
Here is a 11 commands & 53 steps for lvl 24 by myself (@drallieiv)

```
-- HUMAN RESOURCE MACHINE PROGRAM --

a:
    INBOX   
    COPYTO   0
    INBOX   
    COPYTO   1
    COPYFROM 0
b:
    SUB      1
    JUMPN    c
    JUMP     b
c:
    ADD      1
    OUTBOX  
    JUMP     a


DEFINE LABEL 0
eJzjYWBgmKDjfr7Y/OSiV1ZaPQl2W1IjHFOjzrvMDvZ1rcoUdj53GaiE4ZM5y/yVQe4LGUbBKBgFwwoA
AHzKEfk;

DEFINE LABEL 1
eJyTY2BgOKEvGwqkGI4aJGie0psf5qM3v4XdwHtJs+H8TSDxNoMUnUW2j7SEnVN0Wj1yjf55fTb75tvk
uMWPw+2zX4jfFr+IwD3e88MMLV7HLbXZkirmxFJ40m16HZuHYhtQfd8Rj70z2TwY5kQ4nlxUZ8y71FM/
YDnDKBgFo2BQAADScywL;

DEFINE LABEL 3
eJwTZGBgWGvp7vre4nHbG8tLK4BchhXWsqGSjtf8rzhJBvW7PIo46VaX0+XWXxHgIloLFK9dYd1VmmE9
uTrB7nWPh/u5pQyjYBSMgiELAByyG2I;
```

**Comment by atesgoral** [comment]
Ah! I just merged an exactly 11+53 solution by someone else. Could you please take a look to see if either theirs or your approach seems any better? I'm currently merging contributions only when there's a decrease in size or steps.

Also, for future improvements, please take your time and take a stab at issuing a Pull Request. This guide seems to be nice: https://yangsu.github.io/pull-request-tutorial/

Please let me know if you get stuck. Or let me know if you don't want to deal with it and I can incorporate your improvements on your behalf.

Thanks! :)

**Comment by nanashi-juanto** [comment]
This is in fact exactly the same solution, sorry.
