### ISSUE TITLE
32-Inventory-Report.speed shuld be 32-Inventory-Report.side.speed

### ISSUE THREAD

**Issue by pyaehtetaung** [atesgoral/human-resource-machine-solutions#65]
![32-inventory-report size](https://cloud.githubusercontent.com/assets/5039175/10631371/9868fc04-7803-11e5-82a4-034cc7fae124.png)
32-Inventory-Report.size
side - 16/16
speed - 393/404

![32-inventory-report speed](https://cloud.githubusercontent.com/assets/5039175/10631391/be6635e8-7803-11e5-8899-300272419a2a.png)
32-Inventory-Report.speed
side - 16/16
speed - 393/377

**Comment by atesgoral** [comment]
Thanks for noticing! Will correct this.
