### ISSUE TITLE
25. Cumulative Countdown - Size solution not found

### ISSUE THREAD

**Issue by Gimlao** [atesgoral/human-resource-machine-solutions#87]
« [11/12](https://github.com/atesgoral/human-resource-machine-solutions/blob/master/25-Cumulative-Countdown.size.asm) by @pyaehtetaung »

The URL is good, but the file is still named with "size.speed" instead of "size" only :
https://github.com/atesgoral/human-resource-machine-solutions/blob/master/25-Cumulative-Countdown.size.speed.asm

**Comment by nanashi-juanto** [comment]
Correct, under the current format it would be renamed ".size". However, we are currently discussing in issue #69 about a directory structure overhaul that will separate each problem into its own folder and include filenames indicating single size/speed or both ("normal") optimizations.

**Comment by atesgoral** [comment]
I was just in the middle of fixing this after merging a PR, and then had to leave home. I'm now back, and pushed the fix. Thanks for noticing!
