### ISSUE TITLE
Rename solution files to include size/speed-n-githubusername

### ISSUE THREAD

**Issue by atesgoral** [atesgoral/human-resource-machine-solutions#93]
As proposed in #69, the files that have now been split up into folders need to be renamed by someone or a robot.

**Comment by nanashi-juanto** [comment]
Just got back. 1-20 were done about an hour ago, and I'll now be looking through 21-41.

**Comment by atesgoral** [comment]
@nanashi-juanto I've made you a contributor so you can directly push to master.

**Comment by atesgoral** [comment]
For including the size/speed numbers in file names, we could take advantage of hrm-cpu and automate it (when it becomes able to run all solutions).

**Comment by nanashi-juanto** [comment]
Renamed. Oh, and how do I push all at once so I don't trickle in commits sequentially? I almost understand pushing a local copy but I do not know how to do renames from outside the webpage without it thinking that I deleted and added separate files?

**Comment by atesgoral** [comment]
From the command line Git client you can rename files by:

```
git mv oldname newname
git mv oldname2 newname2
...
git commit -am "Renamed files"
git push origin master
```

**Comment by atesgoral** [comment]
Awesome effort BTW, @nanashi-juanto!
